[package]
name = "frozen_map"
version = "0.1.0"
edition = "2024"

[dependencies]
bitvec = "1.0.1"
ph = {version = "0.10.0", features = ["gxhash", "sux"] }
rand = "0.9.2"


[dependencies.xxhash-rust]
version = "0.8.12"
features = ["xxh3", "const_xxh3"]
